[workspace]
members = ["projects/*"]
default-members = [
    "projects/wolfram-import",
]
exclude = [
    "projects/wolfram-bind",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
